apiVersion: v1
kind: Service
metadata:
  name: fastapi-openai-service
spec:
  selector:
    app: fastapi-openai
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
